### ISSUE TITLE
ch02-01-melody.md claims that one can use +++ to concat arrays

### ISSUE THREAD

**Issue by shimpe** [supercollider/learn#2]
it's probably a typo as the example underneath uses ++ instead

+++ does exist, but it "zips" two lists instead of concatenating them

[ 1, 2, 3 ] +++ [ 4, 5, 6 ]  == [ [ 1, 4 ], [ 2, 5 ], [ 3, 6 ] ]

whereas 

[ 1, 2, 3 ] ++ [ 4, 5, 6 ]  == [ 1, 2, 3, 4, 5, 6 ]

**Comment by cianoc** [comment]
Good catch. Now fixed.
